package it.fitdiary.backend.utility.service;


import it.fitdiary.backend.entity.Utente;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.http.HttpStatus;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.mail.javamail.MimeMessagePreparator;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;

import javax.mail.internet.InternetAddress;
import java.util.Date;

@Component("mailService")
@EnableAutoConfiguration
public class EmailServiceImpl implements EmailService {

    /**
     * Stringa html per la mail che contiene all'interno testo sostituibile,
     * le seguenti stringhe, wrappate in # sono sostituibili con un replace:
     * #UTENTE# = da sostituire con il nome dell'utente
     * #PREPARATORE# = da sostituire con il nome del preparatore
     * #USERNAME# = da sostiturie con l'username/email per l'accesso
     * #PASSWORD# = da sostituire con la password generate per l'accesso. */
    private String html =
        "<!DOCTYPE html>\n"
                + "<html\n"
                + "xmlns:v=\"urn:schemas-microsoft-com:vml\"\n"
                + "xmlns:o=\"urn:schemas-microsoft-com:office:office\"\n"
                + "lang=\"en\"\n"
                + ">\n"
                + "<head>\n"
                + "<title></title>\n"
                + "<meta charset=\"UTF-8\" />\n"
                + "<meta name=\"viewport\" content=\"width=device-width, "
                + "initial-scale=1.0\" />\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family="
                + "Source+Sans+Pro\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Bitter\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family="
                + "Droid+Serif\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Lato\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family="
                + "Merriweather\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Oxygen\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family="
                + "Permanent+Marker\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Nunito\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Oswald\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Cabin\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Open+Sans\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family="
                + "Abril+Fatface\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family="
                + "Montserrat\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Ubuntu\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<link\n"
                + "href=\"https://fonts.googleapis.com/css?family=Roboto\"\n"
                + "rel=\"stylesheet\"\n"
                + "type=\"text/css\"\n"
                + "/>\n"
                + "<!--<![endif]-->\n"
                + "<style>\n"
                + "* {\n"
                + "box-sizing: border-box;\n"
                + "}\n"
                + "\n"
                + "body {\n"
                + "margin: 0;\n"
                + "padding: 0;\n"
                + "}\n"
                + "\n"
                + "a[x-apple-data-detectors] {\n"
                + "color: inherit !important;\n"
                + "text-decoration: inherit !important;\n"
                + "}\n"
                + "\n"
                + "#MessageViewBody a {\n"
                + "color: inherit;\n"
                + "text-decoration: none;\n"
                + "}\n"
                + "\n"
                + "p {\n"
                + "line-height: inherit;\n"
                + "}\n"
                + "\n"
                + "@media (max-width: 660px) {\n"
                + ".icons-inner {\n"
                + "text-align: center;\n"
                + "}\n"
                + "\n"
                + ".icons-inner td {\n"
                + "margin: 0 auto;\n"
                + "}\n"
                + "\n"
                + ".row-content {\n"
                + "width: 100% !important;\n"
                + "}\n"
                + "\n"
                + ".image_block img.big {\n"
                + "width: auto !important;\n"
                + "}\n"
                + "\n"
                + ".menu-checkbox[type=\"checkbox\"] ~ .menu-links {\n"
                + "display: none !important;\n"
                + "padding: 5px 0;\n"
                + "}\n"
                + "\n"
                + ".menu-checkbox[type=\"checkbox\"]:checked ~ "
                + ".menu-trigger .menu-open {\n"
                + "display: none !important;\n"
                + "}\n"
                + "\n"
                + ".menu-checkbox[type=\"checkbox\"]:checked ~ .menu-links,\n"
                + ".menu-checkbox[type=\"checkbox\"] ~ .menu-trigger {\n"
                + "display: block !important;\n"
                + "max-width: none !important;\n"
                + "max-height: none !important;\n"
                + "font-size: inherit !important;\n"
                + "}\n"
                + "\n"
                + ".menu-checkbox[type=\"checkbox\"] ~ .menu-links > a,\n"
                + ".menu-checkbox[type=\"checkbox\"] ~ "
                + ".menu-links > span.label {\n"
                + "display: block !important;\n"
                + "text-align: center;\n"
                + "}\n"
                + "\n"
                + ".menu-checkbox[type=\"checkbox\"]:checked ~ "
                + ".menu-trigger .menu-close {\n"
                + "display: block !important;\n"
                + "}\n"
                + "\n"
                + ".stack .column {\n"
                + "width: 100%;\n"
                + "display: block;\n"
                + "}\n"
                + "}\n"
                + "</style>\n"
                + "</head>\n"
                + "\n"
                + "<body\n"
                + "style=\"\n"
                + "background-color: #14d9f6;\n"
                + "margin: 0;\n"
                + "padding: 0;\n"
                + "-webkit-text-size-adjust: none;\n"
                + "text-size-adjust: none;\n"
                + "\"\n"
                + ">\n"
                + "<table\n"
                + "class=\"nl-container\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "background-color: #14d9f6;\n"
                + "\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td>\n"
                + "<!-- Header  -->\n"
                + "<table\n"
                + "class=\"row row-1\"\n"
                + "align=\"center\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td>\n"
                + "<table\n"
                + "class=\"row-content stack\"\n"
                + "align=\"center\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "background-position: top center;\n"
                + "background-color: #000000;\n"
                + "background-image: url('https://d1oco4z2z1fhwp.cloudfront.net"
                + "/templates/default/3571/bg-top.png');\n"
                + "background-repeat: repeat;\n"
                + "color: #000000;\n"
                + "width: 640px;\n"
                + "\"\n"
                + "width=\"640\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td\n"
                + "class=\"column\"\n"
                + "width=\"100%\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "font-weight: 400;\n"
                + "text-align: left;\n"
                + "vertical-align: top;\n"
                + "padding-top: 0px;\n"
                + "padding-bottom: 0px;\n"
                + "border-top: 0px;\n"
                + "border-right: 0px;\n"
                + "border-bottom: 0px;\n"
                + "border-left: 0px;\n"
                + "\"\n"
                + ">\n"
                + "<!-- Logo  -->\n"
                + "<table\n"
                + "class=\"image_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "width: 100%;\n"
                + "padding-right: 0px;\n"
                + "padding-left: 0px;\n"
                + "padding-top: 35px;\n"
                + "\"\n"
                + ">\n"
                + "<div align=\"center\" style=\"line-height: 10px\">\n"
                + "<img\n"
                + "src=\"https://i.ibb.co/098fc1F/Asset-2xhdpi.png\"\n"
                + "style=\"\n"
                + "display: block;\n"
                + "height: auto;\n"
                + "border: 0;\n"
                + "width: 256px;\n"
                + "max-width: 100%;\n"
                + "\"\n"
                + "width=\"256\"\n"
                + "alt=\"FitDiary Logo\"\n"
                + "title=\"FitDiary Logo\"\n"
                + "/>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Ciao utente benvenuto  -->\n"
                + "<table\n"
                + "class=\"menu_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "color: #ffffff;\n"
                + "font-family: inherit;\n"
                + "font-size: 14px;\n"
                + "padding-bottom: 10px;\n"
                + "padding-top: 45px;\n"
                + "text-align: center;\n"
                + "\"\n"
                + ">\n"
                + "<table\n"
                + "width=\"100%\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "border=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "text-align: center;\n"
                + "font-size: 0px;\n"
                + "\"\n"
                + ">\n"
                + "<input\n"
                + "class=\"menu-checkbox\"\n"
                + "id=\"menugzayxe\"\n"
                + "type=\"checkbox\"\n"
                + "style=\"\n"
                + "display: none !important;\n"
                + "max-height: 0;\n"
                + "visibility: hidden;\n"
                + "\"\n"
                + "/>\n"
                + "<div\n"
                + "class=\"menu-trigger\"\n"
                + "style=\"\n"
                + "display: none;\n"
                + "max-height: 0px;\n"
                + "max-width: 0px;\n"
                + "font-size: 0px;\n"
                + "overflow: hidden;\n"
                + "\"\n"
                + ">\n"
                + "<label\n"
                + "class=\"menu-label\"\n"
                + "for=\"menugzayxe\"\n"
                + "style=\"\n"
                + "height: 36px;\n"
                + "width: 36px;\n"
                + "display: inline-block;\n"
                + "cursor: pointer;\n"
                + "mso-hide: all;\n"
                + "user-select: none;\n"
                + "align: center;\n"
                + "text-align: center;\n"
                + "color: #ffffff;\n"
                + "text-decoration: none;\n"
                + "background-color: transparent;\n"
                + "\"\n"
                + "><span\n"
                + "class=\"menu-open\"\n"
                + "style=\"\n"
                + "mso-hide: all;\n"
                + "font-size: 26px;\n"
                + "line-height: 36px;\n"
                + "\"\n"
                + ">☰</span\n"
                + "><span\n"
                + "class=\"menu-close\"\n"
                + "style=\"\n"
                + "display: none;\n"
                + "mso-hide: all;\n"
                + "font-size: 26px;\n"
                + "line-height: 36px;\n"
                + "\"\n"
                + "></span\n"
                + "></label>\n"
                + "</div>\n"
                + "<div class=\"menu-links\">\n"
                + "<a\n"
                + "href=\"#\"\n"
                + "style=\"\n"
                + "padding-top: 5px;\n"
                + "padding-bottom: 5px;\n"
                + "padding-left: 15px;\n"
                + "padding-right: 15px;\n"
                + "display: inline-block;\n"
                + "color: #ffffff;\n"
                + "font-family: Montserrat,\n"
                + "Trebuchet MS, Lucida Grande,\n"
                + "Lucida Sans Unicode, Lucida Sans,\n"
                + "Tahoma, sans-serif;\n"
                + "font-size: 14px;\n"
                + "text-decoration: none;\n"
                + "letter-spacing: normal;\n"
                + "\"\n"
                + ">Ciao #UTENTE# Benvenuto in\n"
                + "FitDiary</a\n"
                + ">\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Divider  -->\n"
                + "<table\n"
                + "class=\"divider_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"padding-right: 20px; padding-top: 40px\"\n"
                + ">\n"
                + "<div align=\"right\">\n"
                + "<table\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "width=\"35%\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "class=\"divider_inner\"\n"
                + "style=\"\n"
                + "font-size: 1px;\n"
                + "line-height: 1px;\n"
                + "border-top: 10px solid #14d9f6;\n"
                + "\"\n"
                + ">\n"
                + "<span>&#8202;</span>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Immagine  -->\n"
                + "<table\n"
                + "class=\"image_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "width: 100%;\n"
                + "padding-right: 0px;\n"
                + "padding-left: 0px;\n"
                + "padding-top: 10px;\n"
                + "\"\n"
                + ">\n"
                + "<div align=\"center\" style=\"line-height: 10px\">\n"
                + "<img\n"
                + "src=\"https://i.ibb.co/syPhCH9/weights.png\"\n"
                + "style=\"\n"
                + "display: block;\n"
                + "height: auto;\n"
                + "border: 0;\n"
                + "width: 480px;\n"
                + "max-width: 100%;\n"
                + "\"\n"
                + "width=\"480\"\n"
                + "alt=\"Man Lifting Dumbell\"\n"
                + "title=\"Man Lifting Dumbell\"\n"
                + "/>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Preparatore ti aspetta -->\n"
                + "<table\n"
                + "class=\"heading_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "text-align: center;\n"
                + "width: 100%;\n"
                + "padding-top: 40px;\n"
                + "\"\n"
                + ">\n"
                + "<h1\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "color: #14d9f6;\n"
                + "direction: ltr;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "font-size: 35px;\n"
                + "font-weight: normal;\n"
                + "letter-spacing: normal;\n"
                + "line-height: 120%;\n"
                + "text-align: center;\n"
                + "margin-top: 0;\n"
                + "margin-bottom: 0;\n"
                + "\"\n"
                + ">\n"
                + "#PREPARATORE# TI ASPETTA!\n"
                + "</h1>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Accedi subito -->\n"
                + "<table\n"
                + "class=\"heading_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "text-align: center;\n"
                + "width: 100%;\n"
                + "\"\n"
                + ">\n"
                + "<h1\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "color: #14d9f6;\n"
                + "direction: ltr;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "font-size: 36px;\n"
                + "font-weight: normal;\n"
                + "letter-spacing: normal;\n"
                + "line-height: 120%;\n"
                + "text-align: center;\n"
                + "margin-top: 0;\n"
                + "margin-bottom: 0;\n"
                + "\"\n"
                + ">\n"
                + "<strong><em>ACCEDI SUBITO</em></strong>\n"
                + "</h1>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Password e testo -->\n"
                + "<table\n"
                + "class=\"text_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "word-break: break-word;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "padding-top: 30px;\n"
                + "\"\n"
                + ">\n"
                + "<div style=\"font-family: sans-serif\">\n"
                + "<div\n"
                + "style=\"\n"
                + "font-size: 12px;\n"
                + "mso-line-height-alt: 18px;\n"
                + "color: #393d47;\n"
                + "line-height: 1.5;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "\"\n"
                + ">\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: center;\n"
                + "mso-line-height-alt: 24px;\n"
                + "letter-spacing: 1px;\n"
                + "\"\n"
                + ">\n"
                + "<span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "color: #ffffff;\n"
                + "\"\n"
                + ">Una volta dentro potrai inserire i\n"
                + "tuoi dati di partenza e quando\n"
                + "riceverai il protocollo da parte di\n"
                + "#PREPARATORE# potrai cominciare a\n"
                + "seguirlo! Ecco i tuoi dati per\n"
                + "l'accesso:</span\n"
                + ">\n"
                + "</p>\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: center;\n"
                + "letter-spacing: 1px;\n"
                + "mso-line-height-alt: 18px;\n"
                + "\"\n"
                + ">\n"
                + "&nbsp;\n"
                + "</p>\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: center;\n"
                + "mso-line-height-alt: 24px;\n"
                + "letter-spacing: 1px;\n"
                + "\"\n"
                + ">\n"
                + "<span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "color: #ffffff;\n"
                + "\"\n"
                + ">Username: <span>#USERNAME#</span></span\n"
                + ">\n"
                + "</p>\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: center;\n"
                + "mso-line-height-alt: 24px;\n"
                + "letter-spacing: 1px;\n"
                + "\"\n"
                + ">\n"
                + "<span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "color: #ffffff;\n"
                + "\"\n"
                + ">Password: <span>#PASSWORD#</span></span\n"
                + ">\n"
                + "</p>\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: center;\n"
                + "letter-spacing: 1px;\n"
                + "mso-line-height-alt: 18px;\n"
                + "\"\n"
                + ">\n"
                + "&nbsp;\n"
                + "</p>\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: center;\n"
                + "mso-line-height-alt: 24px;\n"
                + "letter-spacing: 1px;\n"
                + "\"\n"
                + ">\n"
                + "<span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "color: #ffffff;\n"
                + "\"\n"
                + ">Ci vediamo su\n"
                + "<a\n"
                + "href=\"http://www.fitdiary.it\"\n"
                + "target=\"_blank\"\n"
                + "style=\"\n"
                + "text-decoration: underline;\n"
                + "color: #d7432a;\n"
                + "\"\n"
                + "rel=\"noopener\"\n"
                + ">www.fitdiary.it</a\n"
                + ">!</span\n"
                + ">\n"
                + "</p>\n"
                + "</div>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Ci vediamo su e tasto -->\n"
                + "<table\n"
                + "class=\"button_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-bottom: 70px;\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "padding-top: 50px;\n"
                + "text-align: center;\n"
                + "\"\n"
                + ">\n"
                + "<div align=\"center\">\n"
                + "<a\n"
                + "href=\"www.fitdiary.it\"\n"
                + "target=\"_blank\"\n"
                + "style=\"\n"
                + "text-decoration: none;\n"
                + "display: inline-block;\n"
                + "color: #000000;\n"
                + "background-color: #f9c212;\n"
                + "border-radius: 0px;\n"
                + "width: auto;\n"
                + "border-top: 1px solid #f9c212;\n"
                + "border-right: 1px solid #f9c212;\n"
                + "border-bottom: 1px solid #f9c212;\n"
                + "border-left: 1px solid #f9c212;\n"
                + "padding-top: 5px;\n"
                + "padding-bottom: 5px;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "text-align: center;\n"
                + "mso-border-alt: none;\n"
                + "word-break: keep-all;\n"
                + "\"\n"
                + "><span\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "font-size: 16px;\n"
                + "display: inline-block;\n"
                + "letter-spacing: normal;\n"
                + "\"\n"
                + "><span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "line-height: 2;\n"
                + "word-break: break-word;\n"
                + "mso-line-height-alt: 32px;\n"
                + "\"\n"
                + "><em\n"
                + "><strong\n"
                + ">Clicca qui ed entra in FitDiary!</strong\n"
                + "></em\n"
                + "></span\n"
                + "></span\n"
                + "></a\n"
                + ">\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<!-- Body  -->\n"
                + "<table\n"
                + "class=\"row row-3\"\n"
                + "align=\"center\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "background-position: top center;\n"
                + "\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td>\n"
                + "<table\n"
                + "class=\"row-content stack\"\n"
                + "align=\"center\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "color: #000000;\n"
                + "width: 640px;\n"
                + "\"\n"
                + "width=\"640\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td\n"
                + "class=\"column\"\n"
                + "width=\"100%\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "font-weight: 400;\n"
                + "text-align: left;\n"
                + "vertical-align: top;\n"
                + "padding-top: 0px;\n"
                + "padding-bottom: 0px;\n"
                + "border-top: 0px;\n"
                + "border-right: 0px;\n"
                + "border-bottom: 0px;\n"
                + "border-left: 0px;\n"
                + "\"\n"
                + ">\n"
                + "<!-- Scopri come migliorare -->\n"
                + "<table\n"
                + "class=\"heading_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "text-align: center;\n"
                + "width: 100%;\n"
                + "padding-top: 40px;\n"
                + "\"\n"
                + ">\n"
                + "<h1\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "color: #ffffff;\n"
                + "direction: ltr;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "font-size: 36px;\n"
                + "font-weight: normal;\n"
                + "letter-spacing: normal;\n"
                + "line-height: 150%;\n"
                + "text-align: right;\n"
                + "margin-top: 0;\n"
                + "margin-bottom: 0;\n"
                + "\"\n"
                + ">\n"
                + "<em\n"
                + "><strong\n"
                + ">SCOPRI COME MIGLIORARE</strong\n"
                + "></em\n"
                + ">\n"
                + "</h1>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Scopri come andare -->\n"
                + "<table\n"
                + "class=\"heading_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "text-align: center;\n"
                + "width: 100%;\n"
                + "\"\n"
                + ">\n"
                + "<h2\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "color: #000000;\n"
                + "direction: ltr;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "font-size: 20px;\n"
                + "font-weight: normal;\n"
                + "letter-spacing: normal;\n"
                + "line-height: 150%;\n"
                + "text-align: right;\n"
                + "margin-top: 0;\n"
                + "margin-bottom: 0;\n"
                + "\"\n"
                + ">\n"
                + "Scopri come andare in palestra migliori la\n"
                + "tua forma mentis\n"
                + "</h2>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Divider -->\n"
                + "<table\n"
                + "class=\"divider_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"padding-right: 20px; padding-top: 20px\"\n"
                + ">\n"
                + "<div align=\"right\">\n"
                + "<table\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "width=\"60%\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "class=\"divider_inner\"\n"
                + "style=\"\n"
                + "font-size: 1px;\n"
                + "line-height: 1px;\n"
                + "border-top: 10px solid #000000;\n"
                + "\"\n"
                + ">\n"
                + "<span>&#8202;</span>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Testo -->\n"
                + "<table\n"
                + "class=\"text_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "word-break: break-word;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "padding-top: 20px;\n"
                + "\"\n"
                + ">\n"
                + "<div style=\"font-family: sans-serif\">\n"
                + "<div\n"
                + "style=\"\n"
                + "font-size: 12px;\n"
                + "mso-line-height-alt: 18px;\n"
                + "color: #393d47;\n"
                + "line-height: 1.5;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "\"\n"
                + ">\n"
                + "<p\n"
                + "style=\"\n"
                + "margin: 0;\n"
                + "font-size: 14px;\n"
                + "text-align: right;\n"
                + "mso-line-height-alt: 24px;\n"
                + "letter-spacing: 1px;\n"
                + "\"\n"
                + ">\n"
                + "<span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "color: #000000;\n"
                + "\"\n"
                + ">Lorem ipsum dolor sit amet,\n"
                + "consectetuer adipiscing elit, sed diam\n"
                + "nonummy nibh euismod tincidunt ut\n"
                + "laoreet dolore magna aliquam erat\n"
                + "volutpatl wisi eo reet dolorr sit\n"
                + "amet, consec hstetuer aquam erat&nbsp;\n"
                + "volutpat. Ut wisi enim ad minim ven\n"
                + "iam, quis nos tl.</span\n"
                + ">\n"
                + "</p>\n"
                + "</div>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<!-- Segui il webinar live -->\n"
                + "<table\n"
                + "class=\"button_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-bottom: 10px;\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "padding-top: 30px;\n"
                + "text-align: right;\n"
                + "\"\n"
                + ">\n"
                + "<div align=\"right\">\n"
                + "<a\n"
                + "href=\"#\"\n"
                + "target=\"_blank\"\n"
                + "style=\"\n"
                + "text-decoration: none;\n"
                + "display: inline-block;\n"
                + "color: #f9c212;\n"
                + "background-color: #000000;\n"
                + "border-radius: 0px;\n"
                + "width: auto;\n"
                + "border-top: 1px solid #000000;\n"
                + "border-right: 1px solid #000000;\n"
                + "border-bottom: 1px solid #000000;\n"
                + "border-left: 1px solid #000000;\n"
                + "padding-top: 5px;\n"
                + "padding-bottom: 5px;\n"
                + "font-family: Montserrat, Trebuchet MS,\n"
                + "Lucida Grande, Lucida Sans Unicode,\n"
                + "Lucida Sans, Tahoma, sans-serif;\n"
                + "text-align: center;\n"
                + "mso-border-alt: none;\n"
                + "word-break: keep-all;\n"
                + "\"\n"
                + "><span\n"
                + "style=\"\n"
                + "padding-left: 20px;\n"
                + "padding-right: 20px;\n"
                + "font-size: 16px;\n"
                + "display: inline-block;\n"
                + "letter-spacing: normal;\n"
                + "\"\n"
                + "><span\n"
                + "style=\"\n"
                + "font-size: 16px;\n"
                + "line-height: 2;\n"
                + "word-break: break-word;\n"
                + "mso-line-height-alt: 32px;\n"
                + "\"\n"
                + "><em\n"
                + "><strong\n"
                + ">SEGUI IL WEBINAR LIVE</strong\n"
                + "></em\n"
                + "></span\n"
                + "></span\n"
                + "></a\n"
                + ">\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<!-- Footer  -->\n"
                + "<table\n"
                + "class=\"row row-9\"\n"
                + "align=\"center\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td>\n"
                + "<table\n"
                + "class=\"row-content stack\"\n"
                + "align=\"center\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "background-color: #000000;\n"
                + "background-image: "
                + "url('https://i.ibb.co/qn0SyVw/bg-top.png');\n"
                + "background-position: center top;\n"
                + "background-repeat: repeat;\n"
                + "color: #000000;\n"
                + "width: 640px;\n"
                + "\"\n"
                + "width=\"640\"\n"
                + ">\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td\n"
                + "class=\"column\"\n"
                + "width=\"100%\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "font-weight: 400;\n"
                + "text-align: left;\n"
                + "vertical-align: top;\n"
                + "padding-top: 0px;\n"
                + "padding-bottom: 0px;\n"
                + "border-top: 0px;\n"
                + "border-right: 0px;\n"
                + "border-bottom: 0px;\n"
                + "border-left: 0px;\n"
                + "\"\n"
                + ">\n"
                + "<table\n"
                + "class=\"image_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "width: 100%;\n"
                + "padding-right: 0px;\n"
                + "padding-left: 0px;\n"
                + "\"\n"
                + ">\n"
                + "<div align=\"center\" style=\"line-height: 10px\">\n"
                + "<img\n"
                + "class=\"big\"\n"
                + "src=\"https://i.ibb.co/TmDSJNj/walking-new.png\"\n"
                + "style=\"\n"
                + "display: block;\n"
                + "height: auto;\n"
                + "border: 0;\n"
                + "width: 640px;\n"
                + "max-width: 100%;\n"
                + "\"\n"
                + "width=\"640\"\n"
                + "alt=\"Man Walking On Treadmill\"\n"
                + "title=\"Man Walking On Treadmill\"\n"
                + "/>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<table\n"
                + "class=\"image_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "width: 100%;\n"
                + "padding-right: 0px;\n"
                + "padding-left: 0px;\n"
                + "padding-top: 30px;\n"
                + "\"\n"
                + ">\n"
                + "<div align=\"center\" style=\"line-height: 10px\">\n"
                + "<img\n"
                + "src=\"https://i.ibb.co/098fc1F/Asset-2xhdpi.png\"\n"
                + "style=\"\n"
                + "display: block;\n"
                + "height: auto;\n"
                + "border: 0;\n"
                + "width: 256px;\n"
                + "max-width: 100%;\n"
                + "\"\n"
                + "width=\"256\"\n"
                + "alt=\"Your Logo\"\n"
                + "title=\"Your Logo\"\n"
                + "/>\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<table\n"
                + "class=\"social_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "padding-bottom: 10px;\n"
                + "padding-left: 10px;\n"
                + "padding-right: 10px;\n"
                + "padding-top: 30px;\n"
                + "text-align: center;\n"
                + "\"\n"
                + ">\n"
                + "<table\n"
                + "class=\"social-table\"\n"
                + "width=\"72px\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "align=\"center\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td style=\"padding: 0 2px 0 2px\">\n"
                + "<a\n"
                + "href=\"https://www.facebook.com/FitDiary21/\"\n"
                + "target=\"_blank\"\n"
                + "><img\n"
                + "src=\"https://i.ibb.co/8KYS1nX/icon2x2.png\"\n"
                + "width=\"32\"\n"
                + "height=\"32\"\n"
                + "alt=\"Facebook\"\n"
                + "title=\"facebook\"\n"
                + "style=\"\n"
                + "display: block;\n"
                + "height: auto;\n"
                + "border: 0;\n"
                + "\"\n"
                + "/></a>\n"
                + "</td>\n"
                + "<td style=\"padding: 0 2px 0 2px\">\n"
                + "<a\n"
                + "href=\"https://www.instagram.com/fitdiary_is/\"\n"
                + "target=\"_blank\"\n"
                + "><img\n"
                + "src=\"https://i.ibb.co/8m9v4xN/instagram2x2.png\"\n"
                + "width=\"32\"\n"
                + "height=\"32\"\n"
                + "alt=\"Instagram\"\n"
                + "title=\"instagram\"\n"
                + "style=\"\n"
                + "display: block;\n"
                + "height: auto;\n"
                + "border: 0;\n"
                + "\"\n"
                + "/></a>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "<table\n"
                + "class=\"menu_block\"\n"
                + "width=\"100%\"\n"
                + "border=\"0\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "color: #ffffff;\n"
                + "font-family: inherit;\n"
                + "font-size: 14px;\n"
                + "padding-bottom: 65px;\n"
                + "padding-top: 10px;\n"
                + "text-align: center;\n"
                + "\"\n"
                + ">\n"
                + "<table\n"
                + "width=\"100%\"\n"
                + "cellpadding=\"0\"\n"
                + "cellspacing=\"0\"\n"
                + "border=\"0\"\n"
                + "role=\"presentation\"\n"
                + "style=\"\n"
                + "mso-table-lspace: 0pt;\n"
                + "mso-table-rspace: 0pt;\n"
                + "\"\n"
                + ">\n"
                + "<tr>\n"
                + "<td\n"
                + "style=\"\n"
                + "text-align: center;\n"
                + "font-size: 0px;\n"
                + "\"\n"
                + ">\n"
                + "<input\n"
                + "class=\"menu-checkbox\"\n"
                + "id=\"menu4ktsag\"\n"
                + "type=\"checkbox\"\n"
                + "style=\"\n"
                + "display: none !important;\n"
                + "max-height: 0;\n"
                + "visibility: hidden;\n"
                + "\"\n"
                + "/>\n"
                + "<div\n"
                + "class=\"menu-trigger\"\n"
                + "style=\"\n"
                + "display: none;\n"
                + "max-height: 0px;\n"
                + "max-width: 0px;\n"
                + "font-size: 0px;\n"
                + "overflow: hidden;\n"
                + "\"\n"
                + ">\n"
                + "<label\n"
                + "class=\"menu-label\"\n"
                + "for=\"menu4ktsag\"\n"
                + "style=\"\n"
                + "height: 36px;\n"
                + "width: 36px;\n"
                + "display: inline-block;\n"
                + "cursor: pointer;\n"
                + "mso-hide: all;\n"
                + "user-select: none;\n"
                + "align: center;\n"
                + "text-align: center;\n"
                + "color: #ffffff;\n"
                + "text-decoration: none;\n"
                + "background-color: transparent;\n"
                + "\"\n"
                + "><span\n"
                + "class=\"menu-open\"\n"
                + "style=\"\n"
                + "mso-hide: all;\n"
                + "font-size: 26px;\n"
                + "line-height: 36px;\n"
                + "\"\n"
                + ">☰</span\n"
                + "><span\n"
                + "class=\"menu-close\"\n"
                + "style=\"\n"
                + "display: none;\n"
                + "mso-hide: all;\n"
                + "font-size: 26px;\n"
                + "line-height: 36px;\n"
                + "\"\n"
                + ">✕</span\n"
                + "></label\n"
                + ">\n"
                + "</div>\n"
                + "<div class=\"menu-links\">\n"
                + "<a\n"
                + "href=\"https://www.fitdiary.it/terms\"\n"
                + "style=\"\n"
                + "padding-top: 5px;\n"
                + "padding-bottom: 5px;\n"
                + "padding-left: 15px;\n"
                + "padding-right: 15px;\n"
                + "display: inline-block;\n"
                + "color: #ffffff;\n"
                + "font-family: Montserrat,\n"
                + "Trebuchet MS, Lucida Grande,\n"
                + "Lucida Sans Unicode, Lucida Sans,\n"
                + "Tahoma, sans-serif;\n"
                + "font-size: 14px;\n"
                + "text-decoration: none;\n"
                + "letter-spacing: normal;\n"
                + "\"\n"
                + ">Terms & Condition</a\n"
                + ">\n"
                + "<a\n"
                + "href=\"https://www.fitdiary.it/contactus\"\n"
                + "style=\"\n"
                + "padding-top: 5px;\n"
                + "padding-bottom: 5px;\n"
                + "padding-left: 15px;\n"
                + "padding-right: 15px;\n"
                + "display: inline-block;\n"
                + "color: #ffffff;\n"
                + "font-family: Montserrat,\n"
                + "Trebuchet MS, Lucida Grande,\n"
                + "Lucida Sans Unicode, Lucida Sans,\n"
                + "Tahoma, sans-serif;\n"
                + "font-size: 14px;\n"
                + "text-decoration: none;\n"
                + "letter-spacing: normal;\n"
                + "\"\n"
                + ">Contact Us</a\n"
                + ">\n"
                + "<a\n"
                + "href=\"https://www.fitdiary.it/unsubscribe?email=#EMAIL#\"\n"
                + "style=\"\n"
                + "padding-top: 5px;\n"
                + "padding-bottom: 5px;\n"
                + "padding-left: 15px;\n"
                + "padding-right: 15px;\n"
                + "display: inline-block;\n"
                + "color: #ffffff;\n"
                + "font-family: Montserrat,\n"
                + "Trebuchet MS, Lucida Grande,\n"
                + "Lucida Sans Unicode, Lucida Sans,\n"
                + "Tahoma, sans-serif;\n"
                + "font-size: 14px;\n"
                + "text-decoration: none;\n"
                + "letter-spacing: normal;\n"
                + "\"\n"
                + ">Unsubscribe</a\n"
                + ">\n"
                + "</div>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>\n"
                + "<!-- End -->\n"
                + "</body>\n"
                + "</html>\n";

    /**
     * Mail sender per inviare le email.
     */
    private JavaMailSender mailSender;

    /**
     * @param mailSend JavaMailSender
     */
    @Autowired
    public EmailServiceImpl(final JavaMailSender mailSend) {
        this.mailSender = mailSend;
    }

    private void sendEmail(final MimeMessagePreparator preparator) {
        mailSender.send(preparator); // STEP 2
    }

    /**
     * Questa funzione invia un email ad un indirzzo preso in input, con
     * relativo oggetto e testo.
     *
     * @param emailAddress indirizzo di chi deve ricevere l' indirizzo e-mail.
     * @param oggetto      oggetto da inserire nell' email.
     * @param testo        testo che deve contenere l' email.
     */
    @RequestMapping("/mail")
    @ResponseStatus(HttpStatus.CREATED)
    public void sendSimpleMessage(final String emailAddress,
                                  final String oggetto, final String testo)
            throws MailException {
        String[] destination =
                {"demarcodaniele98@gmail.com", "giaqui@gmail.com",
                        "leonardo.monaco45@gmail.com"};
        MimeMessagePreparator preparator = mimeMessage -> {
            MimeMessageHelper message = new MimeMessageHelper(mimeMessage);
            message.setTo(destination);
            message.setFrom(new InternetAddress("noreply@fitdiary.it"));
            message.setSubject(oggetto);
            message.setSentDate(new Date());
            message.setText(testo);
        };

        sendEmail(preparator);
    }

    /**
     * Questa funzione invia un email ad un utente preso in input, con relativo
     * oggetto e testo.
     *
     * @param newUtente utente di chi deve ricevere l' e-mail.
     * @param password  password dell'utente
     */
    @Override
    public void sendSimpleMessage(final Utente newUtente, final String password)
            throws MailException {
        String mailHtml = this.html;
        mailHtml = mailHtml.replace("#PREPARATORE#",
                newUtente.getPreparatore().getNome());
        mailHtml = mailHtml.replace("#UTENTE#", newUtente.getNome());
        mailHtml = mailHtml.replace("#USERNAME#", newUtente.getEmail());
        mailHtml = mailHtml.replace("#PASSWORD#", password);

        String[] destination =
                {"demarcodaniele98@gmail.com", "giaqui@gmail.com",
                        "leonardo.monaco45@gmail.com"};
        String finalHtml = mailHtml;
        MimeMessagePreparator preparator = mimeMessage -> {
            MimeMessageHelper message = new MimeMessageHelper(mimeMessage);
            message.setTo(destination);
            message.setFrom(new InternetAddress("noreply@fitdiary.it"));
            message.setSubject(String.format(
                    "Ciao %s, il tuo personal trainer %s, "
                           + "ti ha invitato in FitDiary!", newUtente.getNome(),
                    newUtente.getPreparatore().getNome()));
            message.setSentDate(new Date());
            message.setText(finalHtml, true);
        };

        sendEmail(preparator);
    }
}
